# Generated by Django 3.2.4 on 2021-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('kolor', models.CharField(max_length=100)),
                ('wiek', models.CharField(max_length=100)),
            ],
        ),
    ]
